"""add_due_date_to_issues_and_description_to_labels

Revision ID: 8823e7dd65a3
Revises: 45f01b2aa67a
Create Date: 2026-04-22 15:22:40.208484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8823e7dd65a3'
down_revision: Union[str, None] = '45f01b2aa67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('labels', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'description')
    op.drop_column('issues', 'due_date')
    # ### end Alembic commands ###
